# tweet_templates.py

ragebait = {
    "real_madrid": [
        "Refs working overtime again?",
        "DNA of the club: complain first, play later.",
        "Another match, another refereeing controversy.",
        "Funny how decisions always tilt one way.",
        "Madrid crying louder than the Bernabéu crowd.",
        "Victim mentality as usual.",
        "When football fails, blame the refs.",
        "Tradition upheld: excuses before analysis.",
        "Same complaints, different season.",
        "Control the refs, lose control of the game.",
        "Pressure the referee, not the opponent.",
        "Every loss needs a conspiracy.",
        "Classic deflection after a poor performance.",
        "Talking more about refs than football.",
        "Standards drop, excuses rise.",
        "Nothing new from that camp.",
        "Defeat always comes with a narrative.",
        "Another press conference about injustice.",
        "Complaints FC strikes again.",
        "Blame everyone except yourselves."
    ],
    "atletico": [
        "Low block merchants at it again.",
        "Parking the bus isn’t football.",
        "Defending with eleven men behind the ball.",
        "Destroy first, play later.",
        "Anti-football dressed as tactics.",
        "All grit, no creativity.",
        "Another game killed by negativity.",
        "Fear-based football on display.",
        "Ninety minutes of survival mode.",
        "Hope for a counter, nothing else.",
        "Playing not to lose, never to win.",
        "Football reduced to fouls and time-wasting.",
        "Same script every big match.",
        "Pragmatism taken too far.",
        "No ambition, just resistance.",
        "Defensive obsession as identity.",
        "Content with spoiling the game.",
        "Zero risk, zero flair.",
        "Crowd watches, game suffocates.",
        "Tactical caution bordering on cowardice."
    ],
    "man_city": [
        "115 reasons and counting.",
        "Oil money can’t buy history.",
        "Charges louder than the trophies.",
        "Success built on unanswered questions.",
        "Achievements under constant asterisk.",
        "Money talks louder than merit.",
        "Court cases stacked higher than medals.",
        "Dominance funded, not earned.",
        "Records shadowed by allegations.",
        "Titles followed by investigations.",
        "Numbers that never add up.",
        "Financial creativity on display.",
        "Football run like a corporation.",
        "Glory with fine print attached.",
        "Spending your way to success.",
        "Talent assembled, ethics missing.",
        "Success without transparency.",
        "More lawyers than academy graduates.",
        "Legacy still under review.",
        "Wins that raise eyebrows."
    ],
    "psg": [
        "Galácticos without tactics.",
        "Stars FC, team nowhere.",
        "Individual talent, collective chaos.",
        "Marketing project before football club.",
        "Names bigger than performances.",
        "No structure, just spotlight.",
        "Superstars, zero chemistry.",
        "All flash, no balance.",
        "Talent wasted year after year.",
        "Built for posters, not trophies.",
        "Egos over organization.",
        "Eleven individuals, not a team.",
        "Same collapse every season.",
        "Champions League dreams, same ending.",
        "Style sacrificed for celebrity.",
        "Money buys stars, not cohesion.",
        "Football reduced to branding.",
        "No plan beyond talent.",
        "Big names, small identity.",
        "Noise without substance."
    ],
    "yankees": [
        "Payroll FC still crying?",
        "All that money, same excuses.",
        "Spending big, delivering little.",
        "Budget unmatched, results unchanged.",
        "Buying stars, missing cohesion.",
        "Expectations high, execution low.",
        "Another season of disappointment.",
        "Money can’t fix everything.",
        "Same narrative every year.",
        "Resources wasted, questions remain.",
        "Blaming injuries again?",
        "Luxury roster, average output.",
        "Pressure without payoff.",
        "Tradition carrying poor form.",
        "Spending masks deeper issues.",
        "Big market, small answers.",
        "Fans promised more than results.",
        "Payroll inflated, trophies absent.",
        "Excuses louder than celebrations.",
        "Legacy living off the past."
    ]
}

supportive = [
    "Barça control the game. Always.",
    "Trust the process. Visca el Barça.",
    "Dominance through possession and patience.",
    "Football played with intelligence.",
    "Calm, control, confidence.",
    "Style before shortcuts.",
    "Identity visible every match.",
    "Youth and quality combined.",
    "Playing the right way matters.",
    "Control defines this team.",
    "Composure under pressure.",
    "Built on footballing principles.",
    "Progress over panic.",
    "Collective strength on display.",
    "Patience brings results.",
    "Confidence grounded in style.",
    "Game management at its best.",
    "Trust in the system.",
    "Calm execution throughout.",
    "Barça impose their rhythm."
]

general = [
    "Barça imposing their style again.",
    "Football played the right way. #ForçaBarça",
    "Control from the first whistle.",
    "Tempo dictated with authority.",
    "Clean buildup, clear intent.",
    "Possession with purpose.",
    "Movement creating space.",
    "Technical quality on display.",
    "Game shaped through control.",
    "Structured football, clear ideas.",
    "Confidence in every phase.",
    "Ball circulation setting the tone.",
    "Pressure applied intelligently.",
    "Playing through the lines.",
    "Composed performance overall.",
    "Team moving as one unit.",
    "Intent visible from kickoff.",
    "Clear identity on the pitch.",
    "Discipline matched with creativity.",
    "Another controlled performance."
]